[package]
name = "file_endec"
version = "1.0.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]
edition = "2018"

[lib]
name = "file_endec"
path = "src/lib.rs"

[[bin]]
name = "fileenc"
path = "src/encrypt.rs"

[[bin]]
name = "filedec"
path = "src/decrypt.rs"

[dependencies]
# command line interaction
structopt = { version = "^0.3.7", default-features = false }
indicatif = "^0.13.0"
rpassword = "^4.0.4"

# encyrption and decryption
rand = "^0.7.2"
ring = "^0.16.9"
secstr = "^0.3.2"

# headers
semver = "^0.9.0"
data-encoding = "^2.1.2"

# compression
brotli = "^3.3.0"

# utilities
lazy_static = "^1.4.0"
