
name: 'Publish file_endec'

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Publish (Dockerhub)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine tag
        uses: allenevans/set-env@v2
        with:
          TAG: $(python -c 'from re import findall as f; from os import environ as e; ref = e.get("GITHUB_REF", "latest").split("/")[-1]; tag = f(r"^v?\d+\.\d+\.\d+", ref); print(tag[0][1:] if tag else "latest")')
      - name: Show tag
        run: |
          echo "TAG=${TAG}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mverleg
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine tag
        run: |
          TAG="$(python -c 'from re import findall as f; from os import environ as e; ref = e.get("GITHUB_REF", "latest").split("/")[-1]; tag = f(r"^v?\d+\.\d+\.\d+", ref); print(tag[0][1:] if tag else "latest")')" && \
          printf "TAG=${TAG}\n" && \
          printf "TAG=${TAG}\n" >>  $GITHUB_ENV
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: mverleg/file-endec:${{ env.TAG }}
          push: true

