
name: 'Test file_endec'

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build .
